name: authentication_repository

environment:
  sdk: '>=3.1.0 <4.0.0'

dev_dependencies:
  flutter_lints: ^2.0.0

dependencies:
  firebase_auth: ^4.8.0
  equatable: ^2.0.5
  google_sign_in: ^6.1.5
  google_sign_in_web: ^0.12.0+5
  firebase_core: ^2.15.1
  kakao_flutter_sdk_user: ^1.5.0
  http: ^1.1.0


