name: authentication_repository

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  flutter_lints: ^2.0.0

dependencies:
  firebase_auth: ^4.12.0
  equatable: ^2.0.5
  google_sign_in: ^6.1.5
  hooks_riverpod: ^2.4.0
  cloud_firestore: ^4.12.0
  kakao_flutter_sdk: ^1.6.0
  syncfusion_flutter_datagrid: ^23.1.36
  syncfusion_flutter_core: ^23.1.36
